# Generated by Django 5.0.6 on 2024-06-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='contact_name',
            new_name='contact',
        ),
    ]
